name = "ThreadsXBenchmarks"
uuid = "b2980a5c-e050-44cc-9034-128659d9d5fd"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
